name: Nightly Intel

on:
  schedule:
    - cron: '0 18 * * *'        # 18:00 UTC  ≈ 02:00 SGT
  workflow_dispatch:

jobs:
  run-intel:
    runs-on: ubuntu-latest

    # ✅ allow pushes & read secrets
    permissions:
      contents: write

    env:
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
      NOTIFY_WEBHOOK_URL:  ${{ secrets.NOTIFY_WEBHOOK_URL }}   # Slack or Lark

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # OPTIONAL – uncomment next 4 lines if you prefer the cache live in CI
      - name: Start Qdrant
        run: docker run -d -p 6333:6333 qdrant/qdrant:latest
        timeout-minutes: 1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run nightly script
        run: node scripts/nightly.js

      - name: Commit reports
        run: |
          git config --global user.email "bot@intel.run"
          git config --global user.name  "Intel Bot"
          git add reports/*.md || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: nightly intel (${{ github.run_id }})"
            git push
          fi

